site_name: CS Masters Application
site_author: 'csmsapp'
copyright: '&copy; 2022 csmsapp'
theme:
  name: material
  custom_dir: overrides
  palette:
  - scheme: default
    primary: blue
    accent: amber
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.top
    - toc.follow
    - navigation.instant
  favicon: images/logo.png
  icon:
    logo: material/school
    repo: fontawesome/brands/github
markdown_extensions:
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - CS Masters Application:
    - Home: index.md
    - 内容征集: 内容征集.md
    - 使用指南: 使用指南.md
    - 选校梯度: 选校梯度.md
$programs_list
    - 外部链接: 外部链接.md
    - CS选校之禅: CS选校之禅.md
    - 贡献者: 贡献者.md
    - 赞赏计划: 赞赏计划.md
  - DataPoints: DataPoints.md
  - 提交DataPoints:
    - 提交指引: 提交DataPoints.md
    - 申请者信息收集表: 申请者信息收集表.md
    - DataPoints收集表: DataPoints收集表.md
    - 提交新项目: 提交新项目.md
extra:
  homepage: /选校梯度/
  social:
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=yAmXwWYl
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HeB9QXZdFR
  analytics:
    provider: google
    property: G-MWWFQ6MJG4
repo_url: https://github.com/csmsapp/csmsapp.github.io
repo_name: csmsapp
edit_uri: edit/master/docs/
extra_css:
  - stylesheets/extra.css
