name: ci 
on:
  push:
    branches:
      - master
    pull_request:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check source code
        uses: actions/checkout@main
      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@main
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: python ./script.py
      - run: mkdocs gh-deploy --force
